### PR TITLE
Fix types issue

### PR DESCRIPTION
**Pull request by BjornTheProgrammer**
Awesome library here!

My code threw linting errors from this package, because `SubtleCryptoImportKeyAlgorithm` wasn't defined. I looked at the tsconfig, and the types were added incorrectly. This fixes that, by just adding the version to cloudflare types.

### CODE REVIEW

**Comment by tsndr** [comment]
Hey, thanks for using my library :)

I've checked in multiple editors and I can't reproduce your issue. Are you sure this isn't a misconfiguration on your side?

**Comment by BjornTheProgrammer** [comment]
The error was coming from tsc with a tsconfig that didn’t skip lib checking. Additionally it was part of my modification of a Google lib. So I’m pretty sure. Does the new change break your editor?

**Comment by tsndr** [comment]
It's not about if it works in my editor with your change or not, I just want to keep the `@cloudflare/workers-types` up-to-date and not have to set them to a fixed version.

**Comment by BjornTheProgrammer** [comment]
You're completely right lol, tested on the same repo, and my fix didn't actually fix it. My editor lied!

```
> gtoken@7.1.0 compile
> tsc -p .

node_modules/@tsndr/cloudflare-worker-jwt/index.d.ts:10:20 - error TS2304: Cannot find name 'SubtleCryptoImportKeyAlgorithm'.

10     [key: string]: SubtleCryptoImportKeyAlgorithm;
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/@tsndr/cloudflare-worker-jwt/index.d.ts:10
```

I've fixed the actual issue, by explicity adding in the import, so that it gets included in the build. This should actually fix it. Sorry about that!

**Comment by BjornTheProgrammer** [comment]
I don't know why this was closed. I amended this commit to adding the import explicitly, which fixes the issue, otherwise without skip lib check enabled, tsc will still throw errors.

**Pull request closed without merging**
