### PR TITLE
fix for base64 secrets

### LINKED ISSUE #15: Can't verify external tokens
`jwt.verify` always returns false when I try to verify tokens I receive from Twitch.
Also when I try to send a request to the Twitch API it returns an error saying it could not verify the token generated by `jwt.sign`

I think Twitch is expecting a token signed with a base64 encoded secret but when I decode the tokens generated by `jwt.sign` it doesn't seem be using a base64 encoded secret.

### PR DESCRIPTION
**Pull request by badoge**
fixes #15 

I was still having the same issue with 1.4.1 but I played around with it and replacing 
https://github.com/tsndr/cloudflare-worker-jwt/blob/594cdd6c05e2b0f137a7d0b53340cd212a9e9ba5/index.js#L114 and https://github.com/tsndr/cloudflare-worker-jwt/blob/594cdd6c05e2b0f137a7d0b53340cd212a9e9ba5/index.js#L77

with `keyData = Base64URL.parse(secret)` fixed the issue for me but I also needed to add a check for non base64 secrets.

### CODE REVIEW

**Comment by tsndr** [comment]
Can you please verify if this is still the case with [v2.0.0](https://github.com/tsndr/cloudflare-worker-jwt/releases/tag/v2.0.0)?

**Comment by badoge** [comment]
Issue is still there on 2.0.0

**Comment by tsndr** [comment]
Unfortunatly those changes make the test fail.

Screen Shot 2022-06-30 at 11 54 49 AM

**Comment by tsndr** [comment]
So if you can implement it without breaking `HSxxx` I will merge it :)

**Comment by badoge** [comment]
I updated the PR to use the 2.0.0 source, but I'm not confident that it will be reliable and was instead thinking of adding an extra parameter to sign() and verify() to indicate that the secret is base64 encoded

**Pull request merged**
